version: 1.0.{build}

branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2015
clone_folder: c:\projects\SharedSimulation

environment:
  matrix:
    - BUILD_MODE: Debug
      OPENGL: ON
    - BUILD_MODE: Release
      OPENGL: ON
    - BUILD_MODE: Debug
      OPENGL: OFF
    - BUILD_MODE: Release
      OPENGL: OFF

matrix:
    fast_finish: true

platform: x64

install:
  # todo: download and install vulkan here
  - set VULKAN=ON
  - set SHARED=OFF

  - mkdir %APPVEYOR_BUILD_FOLDER%\deps
  - cd %APPVEYOR_BUILD_FOLDER%\deps

  - echo Downloading Vulkan SDK
  - appveyor DownloadFile https://www.dropbox.com/s/xrajzwwtuarpvyx/vulkan-1.0.46.0.zip?dl=1
  - 7z x vulkan-1.0.46.0.zip
  - dir vulkan-1.0.46.0

  - copy vulkan-1.0.46.0\*.dll C:\Windows\System32\

  - set VULKAN_SDK=%APPVEYOR_BUILD_FOLDER%\deps\vulkan\VulkanSDK\1.0.46.0
  - set PATH=%VULKAN_SDK%\Bin;%PATH%

build:
  parallel: true  # enable MSBuild parallel builds
  verbosity: minimal

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%

  ############################################################################
  # Build main simulation library without tests
  ############################################################################
  - mkdir build-no-tests
  - cd build-no-tests
  - cmake -DCMAKE_GENERATOR_PLATFORM=%PLATFORM% ^
          -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\build-no-tests ^
          -DBUILD_SHARED_TESTS=OFF ^
          -DUSE_VULKAN=%VULKAN% ^
          -DUSE_OPENGL=%OPENGL% ^
          -DUSE_GLFW=ON ^
          -DUSE_GLM=ON ^
          -DUSE_GUI=ON ^
          -DBUILD_SHARED_LIBS=%SHARED% ^
          ..
  - cmake --build . --target INSTALL --config %BUILD_MODE% -- /m
  - cd ..

  ############################################################################
  # Build main simulation library with tests
  ############################################################################
  - mkdir build-tests
  - cd build-tests
  - cmake -DCMAKE_GENERATOR_PLATFORM=%PLATFORM% ^
          -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\build-tests ^
          -DBUILD_SHARED_TESTS=ON ^
          -DUSE_VULKAN=OFF ^
          -DUSE_OPENGL=OFF ^
          -DUSE_GLFW=ON ^
          -DUSE_GLM=ON ^
          -DUSE_GUI=ON ^
          -DBUILD_SHARED_LIBS=%SHARED% ^
          ..
  - cmake --build . --target INSTALL --config %BUILD_MODE% -- /m
  - cd ..

  ############################################################################
  # Build example projects using simulation library
  ############################################################################
  - cd examples
  - mkdir build
  - cd build
  - cmake -DCMAKE_GENERATOR_PLATFORM=%PLATFORM% -DBUILD_SHARED_LIBS=%SHARED% ..
  - cmake --build . --config %BUILD_MODE% -- /m

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build-tests
  - testbin\testSharedSimulation.exe

notifications:
  - on_build_success: false
  - on_build_failure: true

